version: '3.8'

services:
  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: dhis2-db
    environment:
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB: dhis2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dhis2-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhis -d dhis2"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - dhis2-network

  dhis2:
    image: dhis2/core:2.40.5
    container_name: dhis2-app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DHIS2_DATABASE_HOST: database
      DHIS2_DATABASE_NAME: dhis2
      DHIS2_DATABASE_USERNAME: dhis
      DHIS2_DATABASE_PASSWORD: dhis
      DHIS2_HOME: /opt/dhis2
    ports:
      - "8080:8080"
    volumes:
      - dhis2-data:/opt/dhis2
    restart: unless-stopped
    networks:
      - dhis2-network
    command: >
      sh -c "
      mkdir -p /opt/dhis2 &&
      cat > /opt/dhis2/dhis.conf <<EOF
      connection.dialect = org.hibernate.dialect.PostgreSQLDialect
      connection.driver_class = org.postgresql.Driver
      connection.url = jdbc:postgresql://database:5432/dhis2
      connection.username = dhis
      connection.password = dhis
      EOF
      catalina.sh run
      "

volumes:
  dhis2-db-data:
    name: dhis2-db-data
  dhis2-data:
    name: dhis2-data

networks:
  dhis2-network:
    name: dhis2-network
    driver: bridge
